config/routes.rb
Rails.application.routes.draw do
  root to: 'problems#index'
  resources :problems, only: [:index,:show] do
    collection do
      get 'abc'
    end
    collection do
      get 'cdf'
    end
    collection do
      get 'fgh'
    end
    collection do
      get 'cook'
    end
    collection do
      get 'ccna'
    end
    collection do
      get 'cca'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
def index
end

def show
end

def cook
end

def abc
end

def cdf
end

def fgh
end

def ccna
end

def cca
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooklicense</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <h1 class="grid-6"><a href="/">My License</a></h1>
      </header>
    <%= yield %>
  </body>
</html>

app/views/problems/cca.html.erb
<div class="abc">
<%= form_with url: abc_problems_path, method: :get do |form| %>
<div class="sentence">
【1】PCからサーバA(192.168.1.1)との通信が不可となった。PCからサーバAへpingを打つと、「Reply from 192.168.200.1: TTL expired in transit.」と表示される。このトラブルはOSI参照モデルのどの層が原因だと思われるか、一つ選べ</div>
 <div class="problem" id="problem1">
   <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "1.ネットワーク層",class: 'select-button' %></div>
  <%= form.submit "2.ルーティング層",class: 'select-button'  %></br>
  <%= form.submit "3.アプリケーション層",class: 'select-button'  %></br>
  <%= form.submit "4.セション層",class: 'select-button'  %></br>
  </br>
   <span class='select-message' style='display:none;'>解説</br>
   「TTL expired in transit.」は，IPパケットのTTL(time to live)が0になり，IPパケットが廃棄されたことを示している。</br>
   従って、経路途中にあるルータのルーティング設定ミスが起きているためルーティングループが起きていると考えられる。</br>
   すなわち、IPレベルのトラブルであると考えられるため、第３層のネットワーク層が原因だと分かる。</span>
</div>
</br>
<div class="sentence">
【2】データ送信の際、ホストＡとホストＢは３ウエイハンドシェイク方式でデータのやり取りを行なった。この通信方式はOSI参照モデルの第何層にあたるか、一つ選べ</div>
 <div class="problem" id="problem2">
<%= form.submit "1.物理層",class: 'select-button' %>
</br>
  <%= form.submit "2.セション層",class: 'select-button'  %></br>
   <div class="option">
    <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "3.トランスポート層",class: 'select-button'  %></div>
  <%= form.submit "4.データリンク層",class: 'select-button'  %></br>
   <span class='select-message' style='display:none;'>解説</br>
   ３ウェイハンドシェイク方式とは、いわゆるTCPなどのコネクション型通信を指す。</br>
   第４層のトランスポート層がこの方式にあたる</span>
   </div>
</br>
<div class="sentence">
【3】次の用語の中で、ネットワーク層に相当するものを４つ選べ</div>
<div class="problem" id="problem3">
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "1.ICMP ",class: 'select-button' %></div>
  <%= form.submit "2.UDP",class: 'select-button'  %></br>
  <%= form.submit "3.フレーム",class: 'select-button'  %></br>
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "4.ARP",class: 'select-button'  %></div>
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "5.ルーティング",class: 'select-button'  %></div>
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "6.パケット",class: 'select-button'  %></div>
  <%= form.submit "7.セグメント",class: 'select-button'  %></br>
   <span class='select-message' style='display:none;'>解説</br>
   ICMPはネットワークの障害を調べる為に使われるプロトコル</br>
   ARPはIPアドレスから物理層のネットワーク・アドレス(MACアドレス)を求めるために利用されるプロトコル</br>
   ルーティングはデータを目的地まで送信するための制御のこと</br>
   パケットはデータ通信ネットワークを流れるデータの単位のこと</span>
   </div>
</br>
<div class="sentence">
【4】トランスポート層に相当する機能を次の選択肢の中から２つ選べ</div>
<div class="problem" id="problem4">
  <%= form.submit "1.文字コードや圧縮形式をネットワーク共通の形式に変換する",class: 'select-button' %></br>
  <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "2.欠けたパケットがないか、順序正しく受け取っているかをチェックして通信を確実に行う",class: 'select-button'  %></div>
  <%= form.submit "3.暗号化の方法を機器共通の形式に変換する",class: 'select-button'  %></br>
   <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "4.受けたデータがどのようなアプリケーションを要求しているのかを調べて，セッション層以降の上位プロトコルへ渡す",class: 'select-button'  %></div>
   <span class='select-message' style='display:none;'>解説</br>
   1と3はプレゼンテーション層</span>
   </div>
</br>
<div class="sentence">
【5】データのカプセル化における、各レイヤの説明で、正しいものを１つ選べ</div>
<div class="problem" id="problem5">
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "1.トランスポート層で制御データを付加する、このデータをセグメントという",class: 'select-button' %></div>
  <%= form.submit "2.送信したい元データが物理層にあたる",class: 'select-button'  %></br>
  <%= form.submit "3.レイヤ３でセグメントに制御データを付加する。このデータをフレームという",class: 'select-button'  %></br>
  <%= form.submit "4.レイヤ２でセグメントに制御データを付加する。このデータをパケットという",class: 'select-button'  %></br>
   <span class='select-message' style='display:none;'>解説</br>
   2はアプリケーション層</br>
   3はフレームではなくパケット</br>
   レイヤ2で付加するのはセグメントではなくパケット、そのデータはフレーム</span>
   </div>
</br>
<div class="sentence">
【6】次のうち、クラスフルルーティングプロトルはどれか、１つ選べ</div>
<div class="problem" id="problem6">
  <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "1.RIPv1",class: 'select-button' %></div>
  <%= form.submit "2.RIPv2",class: 'select-button'  %></br>
  <%= form.submit "3.EIGRP",class: 'select-button'  %></br>
  <%= form.submit "4.OSPF",class: 'select-button'  %></br>
   <span class='select-message' style='display:none;'>解説</br>
   2、3、4はクラスレスルーティングプロトコル</span>
   </div>
</br>
<div class="sentence">
【7】MTU1500byteの意味として正しいものを一つ選べ</div>
<div class="problem" id="problem7">
  <%= form.submit "1.指定されたインターフェースで送信できる最大フレームサイズが１５００バイトまでである",class: 'select-button' %></br>
  <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "2.指定されたインターフェースで送信できる最大パケットサイズが１５００バイトまでである",class: 'select-button'  %></div>
  <%= form.submit "3.指定されたインターフェースで送信できる最小フレームサイズが１５００バイトまでである",class: 'select-button'  %></br>
  <%= form.submit "4.指定されたインターフェースで送信できる最大セグメントサイズが１５００バイトまでである",class: 'select-button'  %></br>
   <span class='select-message' style='display:none;'>解説</br>
   フレーム、セグメントではなく最大パケットサイズが1500バイト</span>
   </div>
</br>
<div class="sentence">
【8】ＣＳＭＡ／ＣＤ方式において、ＣＳとＭＡとＣＤにあたる説明をそれぞれ一つずつ選べ</div>
<div class="problem" id="problem8">
  <%= form.submit "1.Tokenを受信する",class: 'select-button' %></br>
  <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "2.複数のコンピュータが同時にデータの送信を行い、データの衝突が起こったことを検知する",class: 'select-button'  %></div>
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "3.ケーブルを複数のコンピュータで共用してデータを送信する",class: 'select-button'  %></div>
  <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "4.ケーブル上にすでにデータが流れていないかかどうかをチェックする",class: 'select-button'  %></div>
   <span class='select-message' style='display:none;'>解説</br>
   2はCD、3はMA、4はCS</br>
   1はトークンパッシング方式</span>
   </div>
</br>
<div class="sentence">
【9】show interface serialコマンドで分かる情報はどれか、一つ選べ</div>
<div class="problem" id="problem9">
  <%= form.submit "1.administratively downの場合は、ポートが故障状態となっている",class: 'select-button' %></br>
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "2.line protocol is up/downはレイヤ２の状態を表している",class: 'select-button'  %></div>
  <%= form.submit "3.serial is up/downはレイヤ３の状態を表している",class: 'select-button'  %></br>
  <%= form.submit "4.serial is downの状態でもline protocol is upの状態はあり得る",class: 'select-button'  %></br>
   <span class='select-message' style='display:none;'>解説</br>
   1.administratively downは管理者権限でダウンさせている状態</br>
   3.serialはレイヤ１の状態</br>
   4.レイヤ１がダウンしている状態でレイヤ２のアップはありえない</span>
   </div>
</br>
<div class="sentence">
【10】各プロトコルのポート番号の組み合わせは誤っているものはどれか、1つ選べ</div>
<div class="problem" id="problem10">
  <%= form.submit "1.TELNET:23",class: 'select-button' %></br>
  <%= form.submit "2.SMTP:25",class: 'select-button'  %></br>
  <%= form.submit "3.HTTP:80",class: 'select-button'  %></br>
  <%= form.submit "4.DNS:53",class: 'select-button'  %></br>
    <div class="option">
  <span class='select-message' style='display:none;'>⭕️</span>
  <%= form.submit "5.HTTPS:445",class: 'select-button'  %></div>
   <span class='select-message' style='display:none;'>解説</br>
   HTTPSのポート番号は443</span>
   </div>
<% end %>
</br>
<%= link_to "トップページ", root_path,class: :past__btn  %>
</div>

app/views/problems/ccna.html.erb
<div class="category">
CCNA練習問題
</br>
<%= link_to "IPアドレス問題", cca_problems_path,class: :past__btn  %></br>

</div>

app/views/problems/cook.html.erb
<div class="category">
調理師試験過去問
</br>
<%= link_to "令和元年度10月", abc_problems_path,class: :past__btn  %></br>
<%= link_to "令和元年度12月", cdf_problems_path,class: :past__btn  %></br>
<%= link_to "令和2年度10月", fgh_problems_path,class: :past__btn  %></br>
</div>

app/views/problems/index.html.erb
<div class="category">
<%= link_to "調理師試験練習問題", cook_problems_path,class: :past__btn  %></br>
<%= link_to "CCNA練習問題", ccna_problems_path,class: :past__btn  %>
</div>

app/views/problems/show.html.erb
<div class="category">
調理師試験過去問
</br>
<%= link_to "令和元年度10月", abc_problems_path,class: :past__btn  %></br>
<%= link_to "令和元年度12月", cdf_problems_path,class: :past__btn  %></br>
<%= link_to "令和2年度10月", fgh_problems_path,class: :past__btn  %></br>
</div>